# SPDX-License-Identifier: MIT

description: Dynamic keypress behavior

compatible: "zmk,behavior-dyn-kp"

include: one_param.yaml

properties:
  label:
    type: string
    required: false
  "#sensor-binding-cells":
    type: int
    required: true
    const: 1
