description: ZMK Unicode behavior

compatible: "zmk,behavior-unicode"

include: [behavior.yaml]

properties:
  unicode:
    type: int
    required: true
    description: Unicode code point to emit

binding-cells: []
